name: weather_app
description: A weather app using Flutter and Cubit.

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  http: ^0.13.5
  geolocator: ^10.0.0
  flutter_dotenv: ^5.0.2
  flutter_spinkit: ^5.2.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env    
  